var data=[
    {
        'id':'1000',
        'name':'iphone5s',
        'num':'5',
        'price':4500
    },
    {
        'id':'2000',
        'name':'iphone4s',
        'num':'4',
        'price':3500
    },
    {
        'id':'3000',
        'name':'iphone3s',
        'num':'3',
        'price':2500
    },
    {
        'id':'4000',
        'name':'iphone6s',
        'num':'6',
        'price':6500
    }
];